version: '3.9'

# follow this
# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
services:

  django-app:
    container_name: smd-django-app
    build: 
      context: ./backend
      dockerfile: Dockerfile
    # command: python app/manage.py runserver 0.0.0.0:8000
    # command: gunicorn your_project_name.wsgi:application -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - PG_SERVICE=db
    env_file:
      - ./backend/app/.env
    volumes:
      - ./backend:/usr/src/app/
    depends_on:
      - db
  
  db:
    image: postgres:15
    restart: always
    # the following environment variable should be asigned 
    # to start the image correctly
    # as the image requires the following 3 variables
    # in our case, we defined it to .env file

    # environment:
    #   - POSTGRES_DB= ...
    #   - POSTGRES_USER= ...
    #   - POSTGRES_PASSWORD= ...
    env_file:
      - ./backend/app/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
        
volumes:
  postgres_data:
    driver: local


      

